services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - .env.db
    volumes:
      - ./dev-db.sql:/docker-entrypoint-initdb.d/dev-db.sql
    network_mode: host

  backend:
    image: ghcr.io/al3x-13/tfc-backend:latest
    ports:
      - 3000:3000
    env_file:
      - .env.backend
    network_mode: host

  frontend:
    image: ghcr.io/al3x-13/tfc-frontend:latest
    ports:
      - 5173:5173
    depends_on:
      - backend
    network_mode: host